steps:
  - label: "Java formatting"
    command: ".buildkite/check_java_format.sh"
    plugins:
      - docker#v1.1.1:
          image: "dhalperi/build-base:latest"
  - label: "Python templates"
    command: "cd tests && python3 -m pytest"
    plugins:
      - docker#v1.1.1:
          image: "dhalperi/build-base:latest"
  - label: "Build"
    command:
      - "mkdir workspace"
      - "mvn -f projects install"
      - "cp projects/allinone/target/allinone-bundle-*.jar workspace/allinone.jar"
      - "tar -cf workspace/workdir.tar $(find -maxdepth 1 -mindepth 1 -not -name '.*' -not -name workspace)"
      - "tar -cf workspace/mvn-repo.tar -C /root/.m2/repository/org/batfish ."
    artifact_paths:
      - "workspace/*"
    plugins:
      - docker#v1.1.1:
          image: "dhalperi/build-base:latest"
  - wait
  - label: "allinone project verification"
    command: 
      - "tar -xf workspace/workdir.tar"
      - "mkdir -p /root/.m2/repository/org/batfish"
      - "tar -xf workspace/mvn-repo.tar -C /root/.m2/repository/org/batfish"
      - "mvn -f projects -pl allinone install -am -P '!fast'"
    plugins:
      - docker#v1.1.1:
          image: "dhalperi/build-base:latest"
      - artifacts#v1.2.0:
          download:
            - "workspace/workdir.tar"
            - "workspace/mvn-repo.tar"
  - label: "batfish project verification"
    command: 
      - "tar -xf workspace/workdir.tar"
      - "mkdir -p /root/.m2/repository/org/batfish"
      - "tar -xf workspace/mvn-repo.tar -C /root/.m2/repository/org/batfish"
      - "mvn -f projects -pl batfish install -am -P '!fast'"
    plugins:
      - docker#v1.1.1:
          image: "dhalperi/build-base:latest"
      - artifacts#v1.2.0:
          download:
            - "workspace/workdir.tar"
            - "workspace/mvn-repo.tar"
  - label: "batfish-client project verification"
    command: 
      - "tar -xf workspace/workdir.tar"
      - "mkdir -p /root/.m2/repository/org/batfish"
      - "tar -xf workspace/mvn-repo.tar -C /root/.m2/repository/org/batfish"
      - "mvn -f projects -pl batfish-client install -am -P '!fast'"
    plugins:
      - docker#v1.1.1:
          image: "dhalperi/build-base:latest"
      - artifacts#v1.2.0:
          download:
            - "workspace/workdir.tar"
            - "workspace/mvn-repo.tar"
  - label: "batfish-common-protocol project verification"
    command: 
      - "tar -xf workspace/workdir.tar"
      - "mkdir -p /root/.m2/repository/org/batfish"
      - "tar -xf workspace/mvn-repo.tar -C /root/.m2/repository/org/batfish"
      - "mvn -f projects -pl batfish-common-protocol install -am -P '!fast'"
    plugins:
      - docker#v1.1.1:
          image: "dhalperi/build-base:latest"
      - artifacts#v1.2.0:
          download:
            - "workspace/workdir.tar"
            - "workspace/mvn-repo.tar"
  - label: "coordinator project verification"
    command: 
      - "tar -xf workspace/workdir.tar"
      - "mkdir -p /root/.m2/repository/org/batfish"
      - "tar -xf workspace/mvn-repo.tar -C /root/.m2/repository/org/batfish"
      - "mvn -f projects -pl coordinator install -am -P '!fast'"
    plugins:
      - docker#v1.1.1:
          image: "dhalperi/build-base:latest"
      - artifacts#v1.2.0:
          download:
            - "workspace/workdir.tar"
            - "workspace/mvn-repo.tar"
  - label: "questions project verification"
    command: 
      - "tar -xf workspace/workdir.tar"
      - "mkdir -p /root/.m2/repository/org/batfish"
      - "tar -xf workspace/mvn-repo.tar -C /root/.m2/repository/org/batfish"
      - "mvn -f projects -pl questions install -am -P '!fast'"
    plugins:
      - docker#v1.1.1:
          image: "dhalperi/build-base:latest"
      - artifacts#v1.2.0:
          download:
            - "workspace/workdir.tar"
            - "workspace/mvn-repo.tar"
  - label: "aws ref tests"
    command: ".buildkite/ref_test.sh tests/aws/commands"
    plugins:
      - docker#v1.1.1:
          image: "dhalperi/build-base:latest"
      - artifacts#v1.2.0:
          download: "workspace/allinone.jar"
  - label: "basic ref tests"
    command: ".buildkite/ref_test.sh tests/basic/commands"
    plugins:
      - docker#v1.1.1:
          image: "dhalperi/build-base:latest"
      - artifacts#v1.2.0:
          download: "workspace/allinone.jar"
  - label: "java-smt ref tests"
    command: ".buildkite/ref_test.sh tests/java-smt/commands"
    plugins:
      - docker#v1.1.1:
          image: "dhalperi/build-base:latest"
      - artifacts#v1.2.0:
          download: "workspace/allinone.jar"
  - label: "jsonpath-addons ref tests"
    command: ".buildkite/ref_test.sh tests/jsonpath-addons/commands"
    plugins:
      - docker#v1.1.1:
          image: "dhalperi/build-base:latest"
      - artifacts#v1.2.0:
          download: "workspace/allinone.jar"
  - label: "jsonpathtotable ref tests"
    command: ".buildkite/ref_test.sh tests/jsonpathtotable/commands"
    plugins:
      - docker#v1.1.1:
          image: "dhalperi/build-base:latest"
      - artifacts#v1.2.0:
          download: "workspace/allinone.jar"
  - label: "parsing-errors-tests ref tests"
    command: ".buildkite/ref_test.sh tests/parsing-errors-tests/commands"
    plugins:
      - docker#v1.1.1:
          image: "dhalperi/build-base:latest"
      - artifacts#v1.2.0:
          download: "workspace/allinone.jar"
  - label: "parsing-tests ref tests"
    command: ".buildkite/ref_test.sh tests/parsing-tests/commands"
    plugins:
      - docker#v1.1.1:
          image: "dhalperi/build-base:latest"
      - artifacts#v1.2.0:
          download: "workspace/allinone.jar"
  - label: "experimental ref tests"
    command: ".buildkite/ref_test.sh tests/questions/experimental/commands"
    plugins:
      - docker#v1.1.1:
          image: "dhalperi/build-base:latest"
      - artifacts#v1.2.0:
          download: "workspace/allinone.jar"
  - label: "stable ref tests"
    command: ".buildkite/ref_test.sh tests/questions/stable/commands"
    plugins:
      - docker#v1.1.1:
          image: "dhalperi/build-base:latest"
      - artifacts#v1.2.0:
          download: "workspace/allinone.jar"
  - label: "roles ref tests"
    command: ".buildkite/ref_test.sh tests/roles/commands"
    plugins:
      - docker#v1.1.1:
          image: "dhalperi/build-base:latest"
      - artifacts#v1.2.0:
          download: "workspace/allinone.jar"
  - label: "ui-focused ref tests"
    command: ".buildkite/ref_test.sh tests/ui-focused/commands"
    plugins:
      - docker#v1.1.1:
          image: "dhalperi/build-base:latest"
      - artifacts#v1.2.0:
          download: "workspace/allinone.jar"
branches: "buildkite"
